# Generated by Django 5.0.3 on 2024-04-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycompany',
            name='acquisition_depot',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='delivery_nature',
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='working_days',
            field=models.CharField(default='', max_length=250, verbose_name='Working Days'),
        ),
        migrations.CreateModel(
            name='DeliveryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=1000, verbose_name='Country')),
                ('cities', models.CharField(default='', max_length=1000, verbose_name='Cities')),
                ('mode_of_delivery', models.CharField(default='', max_length=1000, verbose_name='Mode Of Delivery')),
                ('rate', models.FloatField(default=0, verbose_name='Rate Per Kg')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mini.deliverycompany')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=1000, verbose_name='Product Name')),
                ('product_description', models.CharField(default='', max_length=1000, verbose_name='Product Description')),
                ('amount_paid', models.FloatField(default=0, verbose_name='Payment')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
                ('status', models.CharField(default='', max_length=1000, verbose_name='Status')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mini.deliverycompany')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
