# Generated by Django 5.0.3 on 2024-04-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_remove_deliverycompany_acquisition_depot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydestination',
            old_name='cities',
            new_name='one_cities',
        ),
        migrations.RenameField(
            model_name='deliverydestination',
            old_name='country',
            new_name='one_country',
        ),
        migrations.AddField(
            model_name='deliverydestination',
            name='two_cities',
            field=models.CharField(default='', max_length=1000, verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='deliverydestination',
            name='two_country',
            field=models.CharField(default='', max_length=1000, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='user', max_length=250, verbose_name='Status'),
        ),
    ]
